
class PlayerActionKeys(object):
    
    # action keys
    MOVE_LEFT = "MOVE_LEFT"
    MOVE_RIGHT = "MOVE_RIGHT"
    MOVE_UP = "MOVE_UP"
    MOVE_DOWN = "MOVE_DOWN"
    CANCEL_JUMP = "CANCEL_JUMP"
    CANCEL_MOVE = "CANCEL_MOVE" # in x axis
    CANCEL_DASH = "CANCEL_DASH"
    STAND = "STAND"    
    RUN = "RUN"
    JUMP = "JUMP"    
    FALL = "FALL"
    LAND = "LAND"
    ATTACK = "ATTACK"
    DASH = "DASH"
    MIDAIR_DASH = "MIDAIR_DASH"
    DASH_BREAK="DASH_BREAK"    
    STAND_EDGE = "STAND_EDGE"
    HANG = "HANG"
    CLIMB = "CLIMB"
    ANIMATION_SEQUENCE_COMPLETED = "ANIMATION_SEQUENCE_COMPLETED"
#     LEFT_EDGE_NEAR = "LEFT_EDGE_NEAR"
#     RIGHT_EDGE_NEAR = "RIGHT_EDGE_NEAR"
#     PLATFORM_LEFT_END_NEAR = "PLATFORM_LEFT_END_NEAR"
#     PLATFORM_RIGHT_END_NEAR = "PLATFORM_RIGHT_END_NEAR"
 

    
    