
class ActionKeys(object):
    
    # action keys
    MOVE_LEFT = "MOVE_LEFT"
    MOVE_RIGHT = "MOVE_RIGHT"
    MOVE_UP = "MOVE_UP"
    MOVE_DOWN = "MOVE_DOWN"
    CANCEL_JUMP = "CANCEL_JUMP"
    CANCEL_MOVE = "CANCEL_MOVE" # in x axis
    CANCEL_DASH = "CANCEL_DASH"
    STAND = "STAND"    
    RUN = "RUN"
    JUMP = "JUMP"    
    FALL = "FALL"
    LAND = "LAND"
    ATTACK = "ATTACK"
    DASH = "DASH"
    MIDAIR_DASH = "MIDAIR_DASH"
    DASH_BREAK="DASH_BREAK"    
    STAND_EDGE = "STAND_EDGE"
    ACTION_SEQUENCE_EXPIRED = "ACTION_SEQUENCE_EXPIRED"
    LEFT_EDGE_NEAR = "LEFT_EDGE_NEAR"
    RIGHT_EDGE_NEAR = "RIGHT_EDGE_NEAR"
    COLLISION_BELOW = "COLLISION_BELOW"
    COLLISION_ABOVE = "COLLISION_ABOVE"
    COLLIDED_RIGHT_WALL = "COLLIDED_RIGHT_WALL"
    COLLIDED_LEFT_WALL = "COLLIDED_LEFT_WALL"
    PLATFORM_LOST = "PLATFORM_LOST"
    APPLY_GRAVITY = "APPLY_GRAVITY"
    STEP_GAME = "STEP_GAME"
    EXIT_GAME = "EXIT_GAME"
    
    