class LevelActionKeys(object):
    
    APPLY_GRAVITY = "APPLY_GRAVITY"    
    STEP_GAME = "STEP_GAME"
    EXIT_GAME = "EXIT_GAME"  
    GAME_OBJECT_IN_RANGE = 'GAME_OBJECT_IN_RANGE'
    COLLISION_BELOW = "COLLISION_BELOW"
    COLLISION_ABOVE = "COLLISION_ABOVE"
    COLLISION_RIGHT_WALL = "COLLISION_RIGHT_WALL"
    COLLISION_LEFT_WALL = "COLLISION_LEFT_WALL"
    PLATFORMS_IN_RANGE = "PLATFORMS_IN_RANGE"
    PLATFORM_SUPPORT_LOST = "PLATFORM_SUPPORT_LOST"