class LevelActionKeys(object):
    
    APPLY_GRAVITY = "APPLY_GRAVITY"    
    STEP_GAME = "STEP_GAME"
    EXIT_GAME = "EXIT_GAME"  
    GAME_OBJECT_IN_RANGE = 'GAME_OBJECT_IN_RANGE'
    GAME_OBJECT_COLLISION_RIGHT = 'GAME_OBJECT_COLLISION_RIGHT'
    GAME_OBJECT_COLLISION_LEFT = 'GAME_OBJECT_COLLISION_LEFT'
    GAME_OBJECT_COLLISION_BELOW = 'GAME_OBJECT_COLLISION_BELOW'
    GAME_OBJECT_COLLISION_ABOVE = 'GAME_OBJECT_COLLISION_ABOVE'
    PLATFORM_COLLISION_BELOW = "PLATFORM_COLLISION_BELOW"
    PLATFORM_COLLISION_ABOVE = "PLATFORM_COLLISION_ABOVE"
    PLATFORM_COLLISION_RIGHT = "PLATFORM_COLLISION_RIGHT"
    PLATFORM_COLLISION_LEFT = "PLATFORM_COLLISION_LEFT"
    PLATFORMS_IN_RANGE = "PLATFORMS_IN_RANGE"
    PLATFORM_SUPPORT_LOST = "PLATFORM_SUPPORT_LOST"