

class GameActionKeys(object):
  
  DELIVER_HIT = 'HIT_LANDED'
  TAKE_HIT = 'HIT_TAKEN'
  GRAB_LEDGE = 'LEDGE_REACHED'
  COLLIDE_LANDING_SURFACE = 'LAND'
  COLLIDE_CEILING = 'COLLIDE_CEILING'
  COLLIDE_LEFT_WALL = 'COLLIDE_LEFT_WALL'
  COLLIDE_RIGHT_WALL = 'COLLIDE_RIGHT_WALL'
  
  