
class StateMachineActionKeys(object):
    
    __IGNORE_ACTION__ = 'IGNORE_ACTION'
    SUBMACHINE_START = 'SUBMACHINE_START'
    SUBMACHINE_RESTART = 'SUBMACHINE_RESTART'
    SUBMACHINE_PAUSE = 'SUBMACHINE_PAUSE'
    SUBMACHINE_STOP = 'SUBMACHINE_STOP'
    
    